# Generated by Django 3.1 on 2025-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(default='IN', max_length=10)),
            ],
        ),
    ]
